import { Head } from "@inertiajs/react";
import { Navbar } from "@/Components/Navbar";
import { SiteFooter } from "@/Components/SiteFooter";
import { FAQSection } from "@/Components/FAQSection";
import { useAsset } from "@/hooks/useAsset";
import { Button } from "@/Components/ui/button";
import { Link } from "@inertiajs/react";
import { Check, Leaf, Wind, Box, PiggyBank, Shield, Recycle, ShieldCheck, Droplet, Building2 } from "lucide-react";

const productFaqs = [
    {
        question: "How does the Dubhe Merak STP work?",
        answer: "The Dubhe Merak STP uses advanced biological and mechanical processes to treat domestic and industrial sewage, removing contaminants and producing treated water safe for non-potable reuse."
    },
    {
        question: "What can the treated water be used for?",
        answer: "Treated water from our STPs is ideal for landscaping, gardening, toilet flushing, and other industrial non-potable applications, helping you significantly reduce fresh water consumption."
    },
    {
        question: "Is the system odour-free?",
        answer: "Yes, Dubhe Merak STPs are engineered with efficient aeration and odour control mechanisms to ensure a clean, odour-free operation even in residential environments."
    },
    {
        question: "Do you offer compact units for individual homes?",
        answer: "Absolutely. We provide modular and compact sewage treatment units specifically designed for individual villas and apartments, alongside large-scale systems for commercial complexes."
    }
];

const features = [
    { title: "Eco-Friendly Process", desc: "Uses natural biological processes to break down waste, minimizing the need for harsh chemicals.", icon: Leaf },
    { title: "High-Quality Treated Water", desc: "Produces water that meets regulatory standards for reuse in gardening and other non-potable needs.", icon: Droplet },
    { title: "Compact and Odour-Free", desc: "Designed to operate discreetly with efficient odour control systems, making it suitable for residential areas.", icon: Wind },
    { title: "Customized Capacities", desc: "Systems designed specifically for the volume of waste generated by your facility or home.", icon: Box },
    { title: "Low Operational Cost", desc: "Energy-efficient components and minimal chemical requirements lead to lower long-term costs.", icon: PiggyBank },
    { title: "Durable Construction", desc: "Built with corrosion-resistant materials to ensure a long service life in demanding environments.", icon: Shield }
];

export default function DubheMerak() {
    const asset = useAsset();
    const appBase = asset('');

    return (
        <>
            <Head title=" Branded Water Filtration Plant - Dubhe Merak | Dubhe Richus">
                <meta name="description" content="Choose the Dubhe Merak water treatment plant from Dubhe Richus for dependable iron removal, turbidity reduction, and clean water treatment across Kerala and India." />
            </Head>
            <Navbar />
            <main className="pt-20 bg-slate-50/50">

                {/* ── HERO SECTION ── */}
                <section className="relative py-24 bg-gradient-to-b from-slate-900 to-slate-950 text-white overflow-hidden">
                    <div className="absolute inset-0 bg-[linear-gradient(to_right,#0f172a_1px,transparent_1px),linear-gradient(to_bottom,#0f172a_1px,transparent_1px)] bg-[size:4rem_4rem] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)] opacity-60" />
                    <div className="absolute top-0 right-1/4 w-96 h-96 bg-primary/10 rounded-full blur-3xl" />
                    
                    <div className="mx-auto max-w-7xl px-6 relative z-10">
                        <div className="grid lg:grid-cols-12 gap-12 items-center">
                            {/* Left Side: Product Info */}
                            <div className="lg:col-span-7 space-y-8">
                                <div className="inline-flex items-center gap-2 bg-white/10 border border-white/20 rounded-full px-4 py-1.5 text-xs font-bold uppercase tracking-widest text-white">
                                    <Leaf className="w-3.5 h-3.5" /> Sustainable Wastewater
                                </div>
                                <div className="space-y-4">
                                    <h1 className="text-5xl md:text-7xl font-sans font-black tracking-tight leading-none uppercase bg-gradient-to-r from-white via-slate-100 to-slate-400 bg-clip-text text-transparent">
                                        DUBHE MERAK
                                    </h1>
                                    <h2 className="text-2xl md:text-3xl text-blue-300 font-light tracking-wide uppercase">
                                        Sewage Treatment Plant (STP)
                                    </h2>
                                </div>
                                <p className="text-lg text-slate-200 font-light leading-relaxed max-w-xl text-left">
                                    An elite biological wastewater treatment solution engineered to satisfy strict environmental mandates. Reclaim up to 85% of your facility's black and greywater safely for non-potable reuse, commercial flushing and landscaping with maximum ecological efficiency.
                                </p>
                                
                                {/* Quick Metrics */}
                                <div className="grid grid-cols-3 gap-6 py-6 border-y border-slate-800/80">
                                    <div>
                                        <p className="text-2xl md:text-3xl font-bold text-white">100%</p>
                                        <p className="text-[10px] font-bold uppercase tracking-widest text-slate-300 mt-1">100% Odor-Free Execution</p>
                                    </div>
                                    <div>
                                        <p className="text-2xl md:text-3xl font-bold text-white">85%</p>
                                        <p className="text-[10px] font-bold uppercase tracking-widest text-slate-300 mt-1">Up to 85% Water Recovery Rate</p>
                                    </div>
                                    <div>
                                        <p className="text-2xl md:text-3xl font-bold text-white">Eco</p>
                                        <p className="text-[10px] font-bold uppercase tracking-widest text-slate-300 mt-1">100% Eco & Regulatory Compliant</p>
                                    </div>
                                </div>

                                <div className="flex flex-wrap gap-4">
                                    <Button asChild className="h-14 px-10 bg-primary hover:bg-primary/90 font-bold uppercase tracking-widest text-sm shadow-xl shadow-primary/20 text-white">
                                        <Link href={appBase + "/contact"}>Request Quote</Link>
                                    </Button>
                                    <a href="#water-loop" className="h-14 px-8 border border-white/40 text-white hover:bg-white/10 font-bold uppercase tracking-widest text-xs inline-flex items-center rounded-md transition-colors">
                                        View Water Loop
                                    </a>
                                </div>
                            </div>

                            <div className="lg:col-span-5 relative group flex justify-center lg:justify-end">
                                <div className="w-full max-w-md rounded-[2.5rem] overflow-hidden shadow-2xl border border-slate-800">
                                    <div className="w-full aspect-square overflow-hidden">
                                        <img 
                                            src={asset('/images/dubhemerak.jpg')} 
                                            alt="Dubhe Merak STP" 
                                            className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
                                        />
                                    </div>
                                    {/* Caption below image */}
                                    <div className="bg-slate-900 px-6 py-4 border-t border-slate-800">
                                        <p className="text-xs font-bold uppercase tracking-widest text-blue-300 mb-0.5">Water Reclamation</p>
                                        <p className="text-base font-bold text-white leading-tight">Advanced Biological STP</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                {/* ── THE WATER RECLAMATION LOOP ── */}
                <section id="water-loop" className="py-24 bg-white border-b border-slate-100">
                    <div className="mx-auto max-w-7xl px-6">
                        <div className="max-w-3xl mb-16">
                            <h2 className="text-xs font-bold uppercase tracking-[0.2em] text-primary mb-3">Reclamation Process</h2>
                            <h3 className="text-4xl font-sans font-light text-slate-900 tracking-tight leading-tight">
                                The Reclamation Process: Waste to Resource
                            </h3>
                        </div>

                        <div className="grid md:grid-cols-3 gap-8 relative">
                            {[
                                { step: "01", title: "Primary Separation & Clarification", desc: "Rapidly screens out physical solids, fats, oils, grease (FOG), and suspended macro-particles.", icon: Box },
                                { step: "02", title: "Biological Digestion", desc: "High-efficiency aerobic microbes actively break down dissolved organic waste, converting complex contaminants into harmless natural elements.", icon: Recycle },
                                { step: "03", title: "Disinfection & Micro-Filtration", desc: "Advanced tertiary polishing eliminates pathogens, rendering the final clear output completely safe, stable, and ready for deployment.", icon: Droplet },
                            ].map((item, i) => {
                                const Icon = item.icon;
                                return (
                                    <div key={i} className="relative p-8 bg-slate-50/50 rounded-3xl border border-slate-100/80 hover:bg-white hover:shadow-xl hover:border-primary/10 transition-all duration-300">
                                        <div className="flex justify-between items-center mb-6">
                                            <span className="text-5xl font-black text-slate-200 font-mono leading-none">{item.step}</span>
                                            <div className="w-12 h-12 bg-primary/5 rounded-2xl flex items-center justify-center">
                                                <Icon className="w-6 h-6 text-primary" />
                                            </div>
                                        </div>
                                        <h4 className="text-xl font-bold text-slate-900 mb-3">{item.title}</h4>
                                        <p className="text-slate-500 font-light leading-relaxed text-sm">{item.desc}</p>
                                    </div>
                                );
                            })}
                        </div>
                    </div>
                </section>

                {/* ── APPLICATIONS SHOWCASE ── */}
                <section className="py-24 bg-slate-900 text-white relative overflow-hidden">
                    <div className="absolute bottom-0 right-0 w-80 h-80 bg-primary/5 rounded-full blur-3xl" />
                    <div className="mx-auto max-w-7xl px-6">
                        <div className="grid lg:grid-cols-12 gap-12 items-center">
                            
                            {/* Left side info */}
                            <div className="lg:col-span-5 space-y-6">
                                <h2 className="text-xs font-bold uppercase tracking-[0.2em] text-blue-400">Applications</h2>
                                <h3 className="text-4xl font-sans font-light tracking-tight text-white leading-tight">
                                     High-Compliance Infrastructure
                                 </h3>
                                <p className="text-slate-300 font-light leading-relaxed">
                                     Our biological sewage treatment plants are engineered to provide maximum water recovery while satisfying strict environmental mandates.
                                 </p>
                                 <ul className="space-y-3 pt-4">
                                     {[
                                         "Private Luxury Villas",
                                         "Apartment Communities & Co-housing",
                                         "Commercial Malls & Office Towers",
                                         "Industrial Parks",
                                     ].map(item => (
                                         <li key={item} className="flex items-center gap-3 text-slate-300 text-sm font-medium">
                                             <div className="w-5 h-5 rounded-full bg-blue-500/10 border border-blue-500/20 flex items-center justify-center shrink-0">
                                                 <Check className="w-3 h-3 text-blue-400" />
                                             </div>
                                             {item}
                                         </li>
                                     ))}
                                 </ul>
                            </div>

                            {/* Right side interactive grid */}
                            <div className="lg:col-span-7 grid sm:grid-cols-2 gap-6">
                                {[
                                    { title: "Private Luxury Villas", desc: "Compact, silent, and entirely Odor-free systems that blend discreetly into high-end residential properties.", stat: "Compact" },
                                    { title: "Apartment Communities & Co-housing", desc: "Reliably manages high-volume surging daily loads with exceptionally stable water recovery.", stat: "High-Volume" },
                                    { title: "Commercial Malls & Office Towers", desc: "Generates massive volumes of high-grade reclaimed water to support massive cooling towers (HVAC) and toilet flushing networks.", stat: "Reclamation" },
                                    { title: "Industrial Parks", desc: "Heavy-duty, corrosion-resistant builds designed to easily clear strict Pollution Control Board (PCB) compliance Audits.", stat: "Compliant" },
                                ].map((item, i) => (
                                    <div key={i} className="bg-slate-800/50 p-8 rounded-3xl border border-slate-700/50 hover:border-blue-500/30 hover:bg-slate-800 transition-all duration-300">
                                        <span className="inline-block bg-blue-500/10 text-blue-300 border border-blue-500/20 rounded-full px-3 py-1 text-[10px] font-bold uppercase tracking-widest mb-4">
                                            {item.stat}
                                        </span>
                                        <h4 className="text-lg font-bold text-white mb-2">{item.title}</h4>
                                        <p className="text-slate-400 font-light leading-relaxed text-xs">{item.desc}</p>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                </section>

                {/* ── FEATURES GRID ── */}
                <section className="py-24 bg-white">
                    <div className="mx-auto max-w-7xl px-6">
                        <div className="mb-16 max-w-3xl">
                            <h2 className="text-xs font-bold uppercase tracking-[0.2em] text-primary mb-3">System Features</h2>
                            <h3 className="text-4xl font-sans font-light text-slate-900 tracking-tight leading-tight">
                                Designed for Sustainable Performance
                            </h3>
                        </div>

                        <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
                            {features.map((item, i) => {
                                const Icon = item.icon;
                                return (
                                    <div key={i} className="p-8 bg-slate-50/50 rounded-3xl border border-slate-100 hover:bg-white hover:shadow-xl hover:border-primary/10 transition-all duration-300">
                                        <div className="w-12 h-12 bg-primary/5 rounded-2xl flex items-center justify-center mb-6">
                                            <Icon className="w-6 h-6 text-primary" />
                                        </div>
                                        <h4 className="text-lg font-bold text-slate-900 mb-2">{item.title}</h4>
                                        <p className="text-slate-500 font-light leading-relaxed text-sm">{item.desc}</p>
                                    </div>
                                );
                            })}
                        </div>
                    </div>
                </section>

                {/* ── DETAILED SPLIT ROW ── */}
                <section className="py-24 bg-slate-50/50 border-t border-slate-100">
                    <div className="mx-auto max-w-7xl px-6">
                        <div className="grid lg:grid-cols-2 gap-16 items-center">
                            <div>
                                <div className="aspect-[4/3] rounded-[2.5rem] overflow-hidden shadow-2xl border border-slate-100">
                                    <img src={asset('/images/merak.jpeg')} alt="Water Reuse" className="w-full h-full object-cover" />
                                </div>
                            </div>
                            <div className="space-y-8">
                                <h3 className="text-4xl font-sans font-light text-slate-900 tracking-tight leading-tight text-left">
                                    Protect Groundwater. Save Capital Resources
                                </h3>
                                <p className="text-slate-600 font-light leading-relaxed text-left">
                                    Dubhe Merak STPs stop pollution at its source, protecting local aquifers and regional water bodies from contamination. By selecting our biological treatment setups, you enhance your property's value, drastically reduce municipal fresh-water dependency and maintain a pristine regulatory record.
                                </p>
                                <div className="grid grid-cols-2 gap-6 pt-4">
                                    <div className="space-y-2 text-left">
                                        <div className="w-8 h-8 rounded-lg bg-primary/5 flex items-center justify-center">
                                            <ShieldCheck className="w-5 h-5 text-primary" />
                                        </div>
                                        <h4 className="font-bold text-slate-900 text-sm">Regulatory Compliance</h4>
                                        <p className="text-slate-500 text-xs font-light">Fully meets regional pollution board parameters.</p>
                                    </div>
                                    <div className="space-y-2 text-left">
                                        <div className="w-8 h-8 rounded-lg bg-primary/5 flex items-center justify-center">
                                            <Recycle className="w-5 h-5 text-primary" />
                                        </div>
                                        <h4 className="font-bold text-slate-900 text-sm">Water Re-use</h4>
                                        <p className="text-slate-500 text-xs font-light">Provides stable water resources for gardening and toilet flushing.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                {/* ── CTA BANNER ── */}
                <section className="bg-primary py-24 text-white relative overflow-hidden">
                    <div className="absolute top-0 right-0 w-96 h-96 bg-white/5 rounded-full blur-3xl -translate-x-1/3" />
                    <div className="mx-auto max-w-5xl px-6 text-center relative z-10 space-y-8">
                        <h2 className="text-4xl md:text-5xl font-sans font-light leading-tight text-white">
                            Invest in Sustainable Wastewater Management
                        </h2>
                        <p className="text-white/80 max-w-xl mx-auto font-light leading-relaxed text-sm">
                            Contact Dubhe Richus to request a consultation and customize the Dubhe Merak sewage treatment plant for your building capacity requirements.
                        </p>
                        <div className="flex justify-center gap-4 pt-4">
                            <Button asChild className="bg-white text-primary hover:bg-slate-100 font-bold px-10 h-14 rounded-xl text-sm tracking-widest shadow-xl transition-all hover:-translate-y-1 active:translate-y-0 shrink-0">
                                <Link href={appBase + "/contact"}>Get in Touch</Link>
                            </Button>
                        </div>
                    </div>
                </section>

                <FAQSection items={productFaqs} title="WASTEWATER TREATMENT FAQS" />
            </main>
            <SiteFooter />
        </>
    );
}
